"""Add balance split and last generation final

Revision ID: 13aaa832737a
Revises: 492504c698c4
Create Date: 2025-12-26 20:15:39.774818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13aaa832737a'
down_revision: Union[str, Sequence[str], None] = '492504c698c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance_free', sa.Integer(), server_default='3', nullable=False))
    op.add_column('users', sa.Column('balance_paid', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_generation_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'last_generation_at')
    op.drop_column('users', 'balance_paid')
    op.drop_column('users', 'balance_free')
    # ### end Alembic commands ###
