"""add post_id to banana_transactions

Revision ID: 4a3f12532bb0
Revises: cfc986216e71
Create Date: 2026-05-05 14:08:52.876625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3f12532bb0'
down_revision: Union[str, Sequence[str], None] = 'cfc986216e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banana_transactions', sa.Column('post_id', sa.String(), nullable=True))
    op.add_column('generation_tasks', sa.Column('deducted_from_paid', sa.Integer(), server_default='0', nullable=False))
    op.add_column('generation_tasks', sa.Column('deducted_from_free', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_tasks', 'deducted_from_free')
    op.drop_column('generation_tasks', 'deducted_from_paid')
    op.drop_column('banana_transactions', 'post_id')
    # ### end Alembic commands ###
