"""add model_type to broadcasts

Revision ID: 57aba244b838
Revises: fecf8c30d8ab
Create Date: 2026-03-07 12:27:54.125546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57aba244b838'
down_revision: Union[str, Sequence[str], None] = 'fecf8c30d8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('model_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'model_type')
    # ### end Alembic commands ###
