"""add_clicks_count_to_broadcasts

Revision ID: 58f33892df16
Revises: e047b3470322
Create Date: 2026-03-11 21:53:07.072305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f33892df16'
down_revision: Union[str, Sequence[str], None] = 'e047b3470322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('clicks_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'clicks_count')
    # ### end Alembic commands ###
