"""Add PaymentAttempt

Revision ID: 75caa9693942
Revises: 9aeae61d7d45
Create Date: 2026-05-14 15:16:18.398016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75caa9693942'
down_revision: Union[str, Sequence[str], None] = '9aeae61d7d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_attempts_payment_id'), 'payment_attempts', ['payment_id'], unique=True)
    op.create_index(op.f('ix_payment_attempts_purchase_id'), 'payment_attempts', ['purchase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_purchase_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_payment_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    # ### end Alembic commands ###
