"""add_indexes_for_performance

Revision ID: 79142c44ab8e
Revises: 58f33892df16
Create Date: 2026-03-11 22:45:19.376401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79142c44ab8e'
down_revision: Union[str, Sequence[str], None] = '58f33892df16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_banana_tx_user_id', 'banana_transactions', ['user_id'], unique=False)
    op.create_index('ix_banana_tx_user_type', 'banana_transactions', ['user_id', 'transaction_type'], unique=False)
    op.create_index('ix_purchases_payment_id', 'purchases', ['payment_id'], unique=True)
    op.create_index('ix_purchases_user_status', 'purchases', ['user_id', 'status'], unique=False)
    op.create_index('ix_users_referrer_id', 'users', ['referrer_id'], unique=False)
    op.create_index('ix_users_source', 'users', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_source', table_name='users')
    op.drop_index('ix_users_referrer_id', table_name='users')
    op.drop_index('ix_purchases_user_status', table_name='purchases')
    op.drop_index('ix_purchases_payment_id', table_name='purchases')
    op.drop_index('ix_banana_tx_user_type', table_name='banana_transactions')
    op.drop_index('ix_banana_tx_user_id', table_name='banana_transactions')
    # ### end Alembic commands ###
