"""add_revenue_usd_ton

Revision ID: 7dd0e90d53ab
Revises: 4a3f12532bb0
Create Date: 2026-05-07 14:45:14.100406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd0e90d53ab'
down_revision: Union[str, Sequence[str], None] = '4a3f12532bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_revenue_usd', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_revenue_ton', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_revenue_ton')
    op.drop_column('users', 'total_revenue_usd')
    # ### end Alembic commands ###
