"""add_analytics_fields

Revision ID: 7e9759af9dbb
Revises: cafbc0a07863
Create Date: 2026-01-09 15:40:36.249994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9759af9dbb'
down_revision: Union[str, Sequence[str], None] = 'cafbc0a07863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banana_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('purchases', sa.Column('tariff_name', sa.String(), nullable=True))
    op.add_column('purchases', sa.Column('user_source', sa.String(), nullable=True))
    op.add_column('purchases', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('purchases', sa.Column('payment_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('total_revenue', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('orders_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('first_purchase_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('had_free_actions_before_purchase', sa.Boolean(), server_default=sa.text('0'), nullable=False))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'had_free_actions_before_purchase')
    op.drop_column('users', 'first_purchase_at')
    op.drop_column('users', 'orders_count')
    op.drop_column('users', 'total_revenue')
    op.drop_column('purchases', 'payment_id')
    op.drop_column('purchases', 'completed_at')
    op.drop_column('purchases', 'user_source')
    op.drop_column('purchases', 'tariff_name')
    op.drop_table('banana_transactions')
    # ### end Alembic commands ###
