"""add last_image_ratio to users

Revision ID: 9aeae61d7d45
Revises: 7dd0e90d53ab
Create Date: 2026-05-12 14:19:55.559689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aeae61d7d45'
down_revision: Union[str, Sequence[str], None] = '7dd0e90d53ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_image_ratio', sa.String(length=10), server_default='1:1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_image_ratio')
    # ### end Alembic commands ###
