"""Add balance split and last generation

Revision ID: a335af9606aa
Revises: 492504c698c4
Create Date: 2025-12-26 19:50:17.061820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a335af9606aa'
down_revision: Union[str, Sequence[str], None] = '492504c698c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance_free', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('balance_paid', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_generation_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'last_generation_at')
    op.drop_column('users', 'balance_paid')
    op.drop_column('users', 'balance_free')
    # ### end Alembic commands ###
