"""add yandex client id to users

Revision ID: b103ed8b8bce
Revises: 7e9759af9dbb
Create Date: 2026-01-25 11:41:42.057059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b103ed8b8bce'
down_revision: Union[str, Sequence[str], None] = '7e9759af9dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем yandex_client_id (вручную)
    op.add_column('users', sa.Column('yandex_client_id', sa.String(length=50), nullable=True))
    

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'yandex_client_id')
    # ### end Alembic commands ###