"""Add video generation tasks table

Revision ID: d6570713a0c1
Revises: b103ed8b8bce
Create Date: 2026-01-26 17:24:21.442426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6570713a0c1'
down_revision: Union[str, Sequence[str], None] = 'b103ed8b8bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_generation_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('source_image_file_id', sa.String(), nullable=False),
    sa.Column('source_image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_video_url', sa.String(), nullable=True),
    sa.Column('result_video_file_id', sa.String(), nullable=True),
    sa.Column('fail_code', sa.String(), nullable=True),
    sa.Column('fail_message', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('video_generation_tasks')
    # ### end Alembic commands ###
