"""add_kie_credits_to_video_tasks

Revision ID: d8abd2677b60
Revises: e2a0865012ee
Create Date: 2026-03-08 16:25:28.873925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8abd2677b60'
down_revision: Union[str, Sequence[str], None] = 'e2a0865012ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_generation_tasks', sa.Column('kie_credits_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_generation_tasks', 'kie_credits_cost')
    # ### end Alembic commands ###
