"""add_visited_shop_at_to_users

Revision ID: e30778c9c8b3
Revises: 6f598798177b
Create Date: 2026-03-08 19:18:31.808962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30778c9c8b3'
down_revision: Union[str, Sequence[str], None] = '6f598798177b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('visited_shop_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'visited_shop_at')
    # ### end Alembic commands ###
