"""add model_type to broadcasts

Revision ID: f7b4a214edbf
Revises: 57aba244b838
Create Date: 2026-03-07 08:58:24.601307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b4a214edbf'
down_revision: Union[str, Sequence[str], None] = '57aba244b838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS idx_purchase_payment_id')    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_purchase_payment_id'), 'purchases', ['payment_id'], unique=True, postgresql_where='(payment_id IS NOT NULL)')
    # ### end Alembic commands ###
