"""add_model_manual_flag_and_generations_count

Revision ID: fecf8c30d8ab
Revises: 6a61b3af8f06
Create Date: 2026-02-28 15:41:03.195719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecf8c30d8ab'
down_revision: Union[str, Sequence[str], None] = '6a61b3af8f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_model_manually_selected', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('generations_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'generations_count')
    op.drop_column('users', 'is_model_manually_selected')
    # ### end Alembic commands ###
